### ISSUE TITLE
Filtering of categorical attributes with more than 50 categories

### ISSUE THREAD

**Issue by thinkh** [datavisyn/lineupjs#113]
**Problem**

If there are more than 50 categories for an attribute, the histograms are no longer shown and it is thus impossible to filter them - the side panel stays empty, which is really confusing.

**Suggestion**

Show the list of categories (similar to the filter) in the side panel, so that the user can directly filter some categories (see mockup)

![image](https://user-images.githubusercontent.com/8986080/39704511-dd8bcb92-520b-11e8-9572-0ac4485016e2.png)

**Comment by sgratzl** [comment]
I agree that a blank summary is suboptimal (like a text: cannot render histogram, too many categoriess) but I don't wanna switch to a list automagically. Moreover, since more than 22 categories should be avoided due to color constraints anyhow the given case is actually not that frequent since the column would be derived as string column.

**Comment by sgratzl** [comment]
invalid histogram is still rendered 

![image](https://user-images.githubusercontent.com/4129778/49330861-cb535080-f594-11e8-84e7-619a8915580a.png)

(60 categories)
