### ISSUE TITLE
created dedicated hierarchy vis

### ISSUE THREAD

**Issue by sgratzl** [datavisyn/lineupjs#41]
* [x] show the current sorting and grouping hierarchy
 * [x] separation line between grouping and sorting
 * [x] toggle sorting order as action
 * [x] remove from sorting as action
 * add via drag-and-drop

**Comment by sgratzl** [comment]
current version in sgratzl/hierarchy branch

![image](https://user-images.githubusercontent.com/4129778/42870145-51058268-8a77-11e8-91ec-d2dbf82fcf0e.png)

open questions:
 * how to add new columns and do an dnd reorder - or is the up/down buttons enough when adding a simple dropdown at the bottom to add and skip the dnd at all since it is more direct

**Comment by thinkh** [comment]
Thanks for your suggestion. I tried it briefly and it looks already good. 👍 

> how to add new columns and do an dnd reorder - or is the up/down buttons enough when adding a simple dropdown at the bottom to add and skip the dnd at all since it is more direct

I assume we need both, dnd and the dropdown. Having a dropdown to add (existing) columns to the grouping/sorting hierarchy is necessary. Because dragging a column from the bottom to the top (into the hierarchy) can be too far away and cumbersome. Alternatively, we could hide the summaries (i.e., forms, histogram) once the user starts dragging the column header in the side panel towards the hierarchies.

As for reordering: I would expect to use dnd to reorder the columns within the hierarchy. Because using the arrows is convenient for one step up or down, but requires a lot of effort and targeting when moving a newly added column to the top. Moreover, the dnd approach would be consistent with the other dnd interactions (e.g., drag columns to reposition or create a group).

Additional point: With the explicit grouping and sorting hierarchies we can turn off the sorting of the columns in the side panel and prevent the jumping of columns in the side panel. Then the column order in the side panel would be consistent with the order in the ranking.

Minor points:
* Rename `Up` to `Move up` and `Down` to `Move Down`
* Rename `Remove` to `Remove from hierarchy` (to make clear that it does not remove the column from the ranking)

**Comment by sgratzl** [comment]
current state:

![hierarchy](https://user-images.githubusercontent.com/4129778/42875828-1eddf26c-8a85-11e8-8286-0e9c5310d91b.gif)

I don't think thank that dnd is really needed since with the buttons you have direct control and you usually have at most 2-3 criteria thus the distance is not big

**Comment by thinkh** [comment]
Yes, that looks good. I assume, if there would be more than two categorical grouping criteria, then it would show the input field for the third one, right?

Do you think we can also add groupings for numerical columns, too? I think, that we need an additional field for the threshold.

**Comment by thinkh** [comment]
Done with PR #44.
